---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screen Shot 2018-01-18 at 22-29-04/Screen Shot 2018-01-18 at 22-29-04.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/224017/articles/279518/master/file/figures/Screen%20Shot%202018-01-18%20at%2022-29-04/Screen%20Shot%202018-01-18%20at%2022-29-04.png"
    folder_url: "/users/224017/articles/279518/master/folder/figures/Screen Shot 2018-01-18
      at 22-29-04"
