---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screen Shot 2018-01-17 at 22-38-59/Screen Shot 2018-01-17 at 22-38-59.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/224017/articles/279518/master/file/figures/Screen%20Shot%202018-01-17%20at%2022-38-59/Screen%20Shot%202018-01-17%20at%2022-38-59.png"
    folder_url: "/users/224017/articles/279518/master/folder/figures/Screen Shot 2018-01-17
      at 22-38-59"
