---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/string_normal_image/string_normal_image.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/224017/articles/279518/master/file/figures/string_normal_image/string_normal_image.png"
    folder_url: "/users/224017/articles/279518/master/folder/figures/string_normal_image"
